[package]
authors = ["The Rust Project Developers"]
name = "std_error"
version = "0.0.0"

[lib]
name = "std_error"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }
alloc = { path = "../liballoc" }
std_unicode = { path = "../libstd_unicode" }
