[package]
authors = ["The Rust Project Developers"]
name = "std_ascii"
version = "0.0.0"

[lib]
name = "std_ascii"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }
alloc = { path = "../liballoc" }
